server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: simulation

  # ===============================
  # SECURITY (RESOURCE SERVER)
  # ===============================
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT}

  # ===============================
  # KAFKA
  # ===============================
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL}
      specific.protobuf.value.type: com.dtcc.simulation.proto.TradeEventOuterClass$TradeEvent

    producer:
      key-serializer: ${KAFKA_KEY_SERIALIZER}
      value-serializer: ${KAFKA_VALUE_SERIALIZER}

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer

    listener:
      ack-mode: record

  # ===============================
  # DATABASE
  # ===============================
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: always
      continue-on-error: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
    show-sql: ${DB_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${DB_FORMAT_SQL}
        dialect: ${DB_DIALECT}

# ===============================
# APPLICATION CONFIG
# ===============================
app:
  kafka:
    trade-topic: ${INCOMING_TRADES_TOPIC}

  rabbitmq:
    stream:
      host: ${RABBITMQ_HOST}
      port: ${RABBITMQ_STREAM_PORT}
      name: ${RABBITMQ_STREAM_NAME}
      username: ${RABBITMQ_USERNAME}
      password: ${RABBITMQ_PASSWORD}

# ===============================
# DOWNSTREAM SERVICES
# ===============================
portfolio:
  service:
    base-url: http://${TRADE_CAPTURE_SERVICE_HOST}:${TRADE_CAPTURE_SERVICE_PORT}
