server:
  port: 8090

spring:
  application:
    name: simulation

  security:
    oauth2:
      client:
        registration:
          gateway-client:
            provider: my-auth-server
            client-id: ${SIMULATION_CLIENT_ID:simulation-service}
            client-secret: ${SIMULATION_CLIENT_SECRET:pms-secret}
            authorization-grant-type: client_credentials
            scope: openid,profile
        provider:
          my-auth-server:
            issuer-uri: ${AUTH_SERVER_URL:http://auth:8081}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      schema.registry.url: ${SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL:http://localhost:8081}
      specific.protobuf.value.type: com.dtcc.simulation.proto.TradeEventOuterClass$TradeEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
    listener:
      ack-mode: record

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pmsdb}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:pms}
    password: ${SIMULATION_DB_PASSWORD:pms}

  sql:
    init:
      mode: always
      continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  kafka:
    trade-topic: ${KAFKA_TRADE_TOPIC:trade-events}
  rabbitmq:
    stream:
      host: ${RABBITMQ_HOST:localhost}
      port: ${RABBITMQ_STREAM_PORT:5552}
      name: ${RABBITMQ_STREAM_NAME:trade-stream}
      username: ${SPRING_RABBITMQ_STREAM_USERNAME}
      password: ${SPRING_RABBITMQ_STREAM_PASSWORD}
      retry:
        max-attempts: ${RABBITMQ_MAX_RETRIES:10}
        delay-ms: ${RABBITMQ_RETRY_DELAY:3000}
portfolio:
  service:
    url: ${API_GATEWAY_URL:http://pms-api-gateway:8080}/simulation
